model:
  name: "CausalVariationalCSJDAD"
  input_dim: 1
  latent_dim: 32
  num_env: 4
  hidden_dim: 64
  features_dim: 64
  lambda_causal: 1.0
  lambda_kl: 0.01
  dt: 0.01
  gamma: 0.3

training:
  batch_size: 16
  epochs: 200
  learning_rate: 0.0005
  weight_decay: 0.0001
  optimizer: "Adam"
  scheduler: "StepLR"
  scheduler_step_size: 15
  scheduler_gamma: 0.5
  early_stopping_patience: 8
  early_stopping_min_improvement: 0.001
  save_interval: 5

data:
  dataset: "Yahoo"
  data_dir: "./data/datasets"
  window_size: 200
  stride: 1
  train_split: 0.7
  val_split: 0.1
  test_split: 0.2
  normalize: true
  yahoo:
    filename: null
    train_ratio: 0.8

evaluation:
  metrics: ["auc", "f1", "precision", "recall"]
  threshold_method: "best_f1"
  threshold_percentile: 85
  fixed_threshold: 0.5

logging:
  log_dir: "./results/logs"
  save_model: true
  model_save_dir: "./results/models"
  log_level: "INFO"
  save_predictions: true
  prediction_save_dir: "./results/predictions"

device:
  use_cuda: true
  cuda_device: 0
  num_workers: 4
  pin_memory: true

random_seed: 42
deterministic: true

experiment:
  name: "yahoo_csjdad_experiment"
  notes: "CSJD-AD anomaly detection experiment on Yahoo dataset"
  tags: ["anomaly_detection", "jump_diffusion", "causal", "yahoo"]
